project:
  type: website
  output-dir: docs
website:
  title: "NEWTEC-Unileon Pipelines"
  navbar:
    left:
      - href: about.qmd
        text: About us
      - href: index.html
        text: Home
      - text: Metagenomes
        menu: 
          - href: Metagenomes_Illumina.qmd
            text: Illumina
          - href: Metagenomes_Nanopore.qmd 
            text: Nanopore
      - text: Genomes
        menu: 
          - href: Genomes_Illumina.qmd
            text: Illumina
          - href: Genomes_Nanopore.qmd
            text: Nanopore
          - href: Hybrid_assembly.qmd
            text: Hybrid assembly

    right: 
      - icon: github 
        aria-label: GitHub
        href: https://github.com/NEWTEC-Unileon
        
      - text: "<img src='LOGO_OFICIAL.png' title='web research group' alt='web research group' style='height:20px;'>"
        href: https://portalcientifico.unileon.es/grupos/8577/detalle

format:
  html:
   # theme: Cerulean
   # css: styles.css
   # toc: true
   # code-fold: false
   # code-tools: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

editor: visual
